version: "3.2"

networks:
  kismet:
  rabbit:
  influx:

services:

  kismet-server:
    image: eewids/kismet-server
    networks:
      - kismet
    ports:
      - "2501:2501"
      - "3501:3501"
    tty: true
    stdin_open: true

  rabbit-server:
    image: rabbitmq
    networks:
      - rabbit 

  kiscap2rabbit:
    build: main/kismet-capture2rabbit 
    networks:
      - kismet
      - rabbit 
    tty: true
    stdin_open: true
    entrypoint:
      - python
      - kismet2rabbit.py
      - --kismet_host
      - kismet-server
      - --rabbit_host
      - rabbit-server
    depends_on:
      - kismet-server
      - rabbit-server
    restart: always 

  kisale2rabbit:
    build: main/kismet-alert2rabbit
    networks:
      - kismet
      - rabbit
    tty: true
    stdin_open: true
    entrypoint:
      - python
      - kismetalert2rabbit.py
      - --kismet_host
      - kismet-server
      - --rabbit_host
      - rabbit-server
    depends_on:
      - kismet-server
      - rabbit-server

#############
## Plugins ##
#############
        #  rogueap:
        #    build: plugins/rogueAP/
        #    networks:
        #      - rabbit
        #    volumes:
        #      - type: bind
        #        source: ./plugins/rogueAP/lists
        #        target: /lists
        #    tty: true
        #    stdin_open: true
        #    depends_on:
        #      - rabbit-server
        #      - kiscap2rabbit
        #      - kisale2rabbit
        #    entrypoint:
        #      - python
        #      - rogueap.py
        #      - --train
        #      - --info

  logprint:
    build: plugins/logprint
    networks:
      - rabbit
    tty: true
    stdin_open: true
    depends_on:
      - rabbit-server
      - kisale2rabbit


###################
## Visualization ##
###################
  telegraf:
    image: telegraf:1.4.0
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    depends_on:
      - rabbit-server
    networks:
      - influx
      - rabbit
    ports:
      - "8092/udp"
      - "8094"
      - "8125/udp"
    restart: always 

  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - influx
    ports:
      - "8086"

  grafana:
    image: grafana/grafana:master
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./etc/grafana/provisioning:/etc/grafana/provisioning
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - influx
    ports:
      - "3000:3000"
    restart: always

        #  kapacitor:
        #    image: kapacitor:1.3.3
        #    environment:
        #      KAPACITOR_HOSTNAME: kapacitor
        #      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
        #    links:
        #      - influxdb
        #    networks:
        #      - influx
        #    ports:
        #      - "9092"

