version: "3.2"

networks:
  rabbit:
  influx:

services:
  rabbit-server:
    image: rabbitmq
    networks:
      - rabbit 
    ports:
      - "5672:5672"

  eewids-parser:
    build: main/eewids-parser
    networks:
      - rabbit 
    tty: true
    stdin_open: true
    entrypoint:
      - python
      - ./eewids-parser.py
      - --rabbit_host
      - rabbit-server
    depends_on:
      - rabbit-server
    restart: always 

#############
## Plugins ##
#############
  rogueap:
    build: plugins/rogueAP/
    networks:
      - rabbit
    volumes:
      - type: bind
        source: ./data/rogueAP
        target: /lists
    tty: true
    stdin_open: true
    depends_on:
      - rabbit-server
      - eewids-parser
    entrypoint:
      - python
      - rogueap.py
      - --train
      - --info
    restart: on-failure

  logprint:
    build: plugins/logprint
    networks:
      - rabbit
    tty: true
    stdin_open: true
    depends_on:
      - rabbit-server
      - eewids-parser
    restart: always


###################
## Visualization ##
###################
  telegraf:
    image: telegraf:1.4.0
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    depends_on:
      - rabbit-server
    networks:
      - influx
      - rabbit
    ports:
      - "8092/udp"
      - "8094"
      - "8125/udp"
    restart: always 

  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - influx
    ports:
      - "8086"

  grafana:
    image: grafana/grafana:master
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./etc/grafana/provisioning:/etc/grafana/provisioning
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - influx
    ports:
      - "3000:3000"
    restart: always

