version: "3"
services:

  kismet-server:
    image: eewids/kismet:latest
    network_mode: host
    ports:
      - "2501"
      - "3501"
    tty: true
    stdin_open: true

  rabbit-server:
    image: rabbitmq
    network_mode: host
    ports:
      - "5672"

  rabbit-recv:
    build: rabbit/rabbit-recv
    network_mode: host
    depends_on:
      - rabbit-server
